name: Cleanup Workflow Runs
on:
  workflow_dispatch: # Allows manual triggering

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0 # Keeps 0 days of history
          keep_minimum_runs: 0
